name: CI

on: [push, pull_request]

jobs:
  verify-code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run the tests with enabled coverage
        run: sbt clean coverage test

      - name: Generate the coverage report
        id: coverage-report
        run: sbt coverageReport

      - name: Check the code coverage report to make sure it meets the minimum threshold
        env:
          MINIMUM_COVERAGE: 80
        run: |
          coverage=$(grep -oP 'all\s+\K\d+(?=%)' target/scala-2.13/scoverage-report/scoverage.xml)
          echo "Code coverage: $coverage%"
          if [ "$coverage" -lt "$MINIMUM_COVERAGE" ]
          then
            echo "Code coverage is below the minimum threshold of $MINIMUM_COVERAGE%"
            exit 1
          else
            echo "Code coverage is above the minimum threshold of $MINIMUM_COVERAGE%"
          fi
          
